name: steps-test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo This is job 1

  job2:
    runs-on: ubuntu-latest
    needs: # defines the steps that need to be completed before this one will run
      - job1
    steps:
      - run: echo This is job 2

  job3:
    runs-on: ubuntu-latest
    needs:
      - job2
    steps:
      - run: echo This is job 3

  job4:
    runs-on: ubuntu-latest
    needs: # multiple steps can 'need' the same step, casuing a branch
      - job2
    steps:
      - run: echo This is job 4
      
  job5:
    runs-on: ubuntu-latest
    needs: # making a substep a matrix separates it from it's sibling steps as its own node
      - job2
    strategy:
      fail-fast: false
      matrix:
        include:
        - step_number: 5
        - step_number: 6
    steps:
      - run: echo This is job ${{ matrix.step_number }}
